spring.application.name=esp32-backend

server.port=9090

# Add your db path
spring.datasource.url=jdbc:sqlite:/root/ESP32/MQTT/iot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Add your backend ip and port, mqtt username and password
mqtt.broker=tcp://111.11.111.111:1883
mqtt.username=user
mqtt.password=password

mqtt.device-id=esp32-s3-001
mqtt.telemetry-topic=iot/esp32-s3-001/telemetry
mqtt.control-topic=iot/esp32-s3-001/control
